# Generated by Django 5.2.13 on 2026-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Manger', 'Manger'), ('team_leader', 'Team Leader'), ('Jonior', 'Jonior'), ('Senior', 'Senior')], default=1),
            preserve_default=False,
        ),
    ]
