# Generated by Django 5.2.13 on 2026-04-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_junior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
    ]
