# Generated by Django 5.2.13 on 2026-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_junior',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manger',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_senior',
        ),
        migrations.AddField(
            model_name='user',
            name='posision',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('junior', 'Junior'), ('senior', 'Senior')], default='User'),
        ),
    ]
