# Generated by Django 5.2.13 on 2026-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_position_remove_user_is_junior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posision',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('junior', 'Junior'), ('senior', 'Senior')], default='user'),
        ),
    ]
