# Generated by Django 5.2.13 on 2026-04-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_posision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='posision',
            new_name='position',
        ),
    ]
