# Generated by Django 5.2.13 on 2026-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_posision_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('junior', 'junior'), ('senior', 'senior')], default='user'),
        ),
    ]
