# Generated by Django 5.2.13 on 2026-04-14 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250, verbose_name='Description Of Project')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='The Time Of Project')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_project', to=settings.AUTH_USER_MODEL, verbose_name='Manger Of The Project')),
                ('members', models.ManyToManyField(related_name='members_project', to=settings.AUTH_USER_MODEL, verbose_name='Responsible Of The Group')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250, verbose_name='Description Of Project')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='The Time Of Project')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_group', to=settings.AUTH_USER_MODEL, verbose_name='Manger Of The Group')),
                ('members', models.ManyToManyField(related_name='members_group', to=settings.AUTH_USER_MODEL, verbose_name='Responsible Of The Group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250, verbose_name='Description Of Task')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='The Time Of Task')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_group', to='projects.group')),
                ('resposible', models.ManyToManyField(related_name='members_task', to=settings.AUTH_USER_MODEL, verbose_name='Responsible Of The Task')),
            ],
        ),
    ]
